server.port=8080

# PostgreSQL Database Configurations
spring.datasource.url=jdbc:postgresql://localhost:5432/qacopilot
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate/JPA DDL configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Gemini API Configuration
gemini.api.key=${GEMINI_API_KEY}
gemini.model=gemini-2.5-flash
